server:
  port: 8082

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://ep-square-smoke-an4y5cm3-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_cFq1YJSnV2vH
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect