spring:
  cloud:
    gateway:
      # --- ESTO VA AQUÍ (Al mismo nivel que routes y globalcors) ---
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "https://elitec-tkd-microservicios.vercel.app"
              - "http://127.0.0.1:5500"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: https://auth-service-production-8fc3.up.railway.app
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0
        - id: student-service
          uri: pure-upliftment-production-1b1f.up.railway.app 
          predicates:
            - Path=/api/alumnos/**
          filters:
            - StripPrefix=0