spring.application.name=academia-backend
server.port=8080

# --- CONEXIÓN HÍBRIDA (DOCKER / LOCAL) ---
# Esto permite que funcione en tu PC y también dentro de Docker
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:taekwondo_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURACIÓN JPA (Para crear tablas auto) ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURACIÓN EUREKA (Para el lunes) ---
# Le decimos que SÍ se registre en el servidor Eureka (cuando exista)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true