server.port=8761
spring.application.name=eureka-server

# El servidor no debe registrarse a sí mismo, él es el jefe
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}